services:
  go:
    container_name: go-app
    build:
      context: .
      dockerfile: docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    restart: always
    tty: true
    working_dir: /app
    volumes:
      - ./:/app
    networks:
      - go_networks

  nginx:
    image: nginx:1.27.2-alpine
    container_name: nginx-app
    restart: unless-stopped
    tty: true
    ports:
      - "80:80"
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d/
      - ./docker/nginx/logs:/var/log/nginx/
    networks:
      - go_networks

networks:
  go_networks:
    driver: bridge